# Generated by Django 4.1.6 on 2023-03-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "artist_id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("monthly_listeners", models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name="MonthlyListeners",
        ),
    ]
